import 'dart:math';

import '../../features/simulator/engine/candle_model.dart';
import '../../features/simulator/engine/level_model.dart';
import '../../features/simulator/engine/script_event_model.dart';

/// ⚠ SYNTHETIC DATA — NOT HISTORICAL. ⚠
///
/// Phase 1 of ROADMAP.md calls for "one hardcoded sample dataset" to get the
/// flash-pause-decision feel right before any real level exists. Every number
/// below is generated by the seeded random walk in this file. It is not any
/// real asset, on any real dates, at any real prices.
///
/// CLAUDE.md forbids presenting invented numbers as historical fact, so this
/// level carries [SimulationLevel.isSyntheticSample] and every screen that
/// shows it labels it as synthetic. It exists to exercise the engine and must
/// be deleted — not "upgraded" — once Phase 2's first real, sourced level
/// lands.
///
/// The pause points' `optimal_action` values are *derived mechanically* from
/// the generated series (did price recover above the pre-drawdown level before
/// the window ended?), never hand-picked, so even here nothing is asserted
/// that the data does not support.
class DevSampleLevel {
  const DevSampleLevel._();

  static const String id = 'dev_synthetic_sample';
  static const String assetLabel = 'SYNTHETIC SAMPLE — NOT A REAL ASSET';
  static const int _seed = 20260901;
  static const int _dayCount = 130;
  static const double _startPrice = 1000;

  /// Indices where the generated series is scripted to break down. Chosen to
  /// give the engine two pause points: an initial crash and a later dead-cat
  /// bounce (ENGINE.md §2 explicitly wants multi-pause levels to work).
  static const int _crashStart = 34;
  static const int _crashEnd = 48;
  static const int _bounceEnd = 62;
  static const int _secondLegEnd = 86;

  static SimulationLevel build() {
    final List<Candle> candles = _generateCandles();
    return SimulationLevel(
      id: id,
      realAssetName: assetLabel,
      startingBalance: 100000,
      candles: candles,
      isSyntheticSample: true,
      pausePoints: _pausePoints(candles),
    );
  }

  /// Beginner mode asks for a set count of calls — Somi's spec is "usually
  /// more than 10", so the sample carries 12.
  ///
  /// Placed at the candles where the series moved most over the preceding
  /// week, so the moments land on real turns in this generated data rather
  /// than on an arbitrary grid. Each `optimal_action` is still derived
  /// mechanically by [_pausePointAt] — nothing here asserts a fact the data
  /// does not support.
  ///
  /// NOTE(data): for the real campaign levels this selection is NOT the
  /// engine's job. Every one of the 12 moments per level needs a sourced
  /// trigger date and a defensible optimal action (LEVELS.md). See the
  /// authoring-cost warning in my Phase 2 report.
  static const int momentCount = 12;

  static List<PausePoint> _pausePoints(List<Candle> candles) {
    const int lookback = 5;
    final List<({int index, double move})> ranked = <({int index, double move})>[
      for (int i = lookback; i < candles.length - lookback; i++)
        (
          index: i,
          move: (candles[i].close - candles[i - lookback].close).abs() /
              candles[i - lookback].close,
        ),
    ]..sort((({int index, double move}) a, ({int index, double move}) b) =>
        b.move.compareTo(a.move));

    // Keep the biggest moves, but never two moments within a week of each
    // other — back-to-back prompts would read as nagging, not tension.
    final List<int> chosen = <int>[];
    for (final ({int index, double move}) candidate in ranked) {
      if (chosen.length >= momentCount) break;
      final bool tooClose = chosen.any(
        (int c) => (c - candidate.index).abs() < lookback + 2,
      );
      if (!tooClose) chosen.add(candidate.index);
    }
    chosen.sort();

    return <PausePoint>[
      for (final int index in chosen)
        _pausePointAt(
          candles: candles,
          index: index,
          flashTreatment: _treatmentFor(candles, index),
          headline:
              'Synthetic sample: generated data, so there is no historical '
              'lesson here — only a check that the engine pauses, scores and '
              'reveals correctly.',
        ),
    ];
  }

  /// Hard red for a sharp fall, soft amber for everything else.
  static FlashTreatment _treatmentFor(List<Candle> candles, int index) {
    final double prior = candles[index - 5].close;
    final double change = (candles[index].close - prior) / prior;
    return change <= -0.08
        ? FlashTreatment.redFlashHard
        : FlashTreatment.amberFlashSoft;
  }

  /// Mechanical rule, shared in spirit with Endless mode (ENGINE.md §6):
  /// if the close recovers above the pre-drawdown peak before the window ends,
  /// staying invested was right (hold when already invested is the safe read);
  /// if it never recovers, selling was defensible.
  static PausePoint _pausePointAt({
    required List<Candle> candles,
    required int index,
    required FlashTreatment flashTreatment,
    required String headline,
  }) {
    double priorPeak = 0;
    for (int i = 0; i <= index; i++) {
      priorPeak = max(priorPeak, candles[i].close);
    }
    final bool recovered = candles
        .sublist(index + 1)
        .any((Candle c) => c.close >= priorPeak);

    return PausePoint(
      triggerIndex: index,
      flashTreatment: flashTreatment,
      optimalAction: recovered ? DecisionAction.buyDip : DecisionAction.sell,
      revealHeadline: headline,
    );
  }

  static List<Candle> _generateCandles() {
    final Random random = Random(_seed);
    // Synthetic dates. They are not real trading days and are never shown
    // during play (blind mode) nor presented as fact at debrief.
    final DateTime start = DateTime(2000);

    final List<Candle> candles = <Candle>[];
    double price = _startPrice;

    for (int day = 0; day < _dayCount; day++) {
      final double drift = _driftFor(day);
      final double noise = (random.nextDouble() - 0.5) * 0.028;
      final double open = price;
      final double close = max(1, open * (1 + drift + noise));

      final double wick = open * (0.004 + random.nextDouble() * 0.012);
      final double high = max(open, close) + wick;
      final double low = max(0.5, min(open, close) - wick);

      candles.add(
        Candle(
          date: start.add(Duration(days: day)),
          open: open,
          high: high,
          low: low,
          close: close,
        ),
      );
      price = close;
    }

    return List<Candle>.unmodifiable(candles);
  }

  /// The scripted shape: calm rise, hard crash, dead-cat bounce, second leg
  /// down, then a full recovery — so both pause points have something real
  /// (within the generated series) to be scored against.
  static double _driftFor(int day) {
    if (day < _crashStart) return 0.004;
    if (day < _crashEnd) return -0.030;
    if (day < _bounceEnd) return 0.016;
    if (day < _secondLegEnd) return -0.014;
    return 0.011;
  }
}
